<a href="https://colab.research.google.com/github/gopalm-ai/Manning_Live_Project-Introduction-to-Braket-API/blob/main/Vectors_Matrices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Workflow: Vectors and Matrices

## Exercise 1 Deliverable

In [ ]:
import math
import cmath
import matplotlib.pyplot as plt
import numpy as np
import functools

In [ ]:
a = np.array([[np.sqrt(2), np.sqrt(2), np.sqrt(2)]])

In [ ]:
a

array([[1.41421356, 1.41421356, 1.41421356]])

In [ ]:
b = a.T

In [ ]:
b

array([[1.41421356],
       [1.41421356],
       [1.41421356]])

In [ ]:
a.dot(b)

array([[6.]])

In [ ]:
c = np.array([[0,0,1],[0,1,0],[1,0,0]])

## Exercise 2 Deliverable

In [ ]:
a = np.array([[1+2j], [2+3j], [4+5j]])

In [ ]:
a

array([[1.+2.j],
       [2.+3.j],
       [4.+5.j]])

In [ ]:
b = np.array([[1+2j, 2+3j, 4+5j], [6+7j, 4+1j, 2+0j]])

In [ ]:
b

array([[1.+2.j, 2.+3.j, 4.+5.j],
       [6.+7.j, 4.+1.j, 2.+0.j]])

In [ ]:
b.dot(a)

array([[-17.+56.j],
       [  5.+43.j]])